language: ruby
rvm:
 - 2.2.1
addons:
 postgresql: "9.3"
 sauce_connect:
  username: "Your Sauce Labs username"
  access_key: "Your Sauce Labs access key"
before_script:
 - psql -c 'create database travis_ci_test' -U postgres
script:
 - RAILS_ENV=test bundle exec rake db:migrate
 - RAILS_ENV=test bundle exec rspec spec
sudo: false