language: ruby
rvm:
 - 2.2.1
# addons:
# 	postgresql: "9.3"
# before_script:
#   - psql -c 'create database travis_ci_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
sudo: false