default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: test_test_development

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  <<: *default
  database: test_test_production
